from __future__ import annotations

import json
from pathlib import Path

from decklint import __version__
from decklint.comparison_report import build_comparison_report


ROOT = Path(__file__).resolve().parents[1]
PROOF = ROOT / "site" / "proof-loop"


def main() -> int:
    before = json.loads((PROOF / "before.json").read_text(encoding="utf-8"))
    after = json.loads((PROOF / "after.json").read_text(encoding="utf-8"))
    comparison = json.loads((PROOF / "comparison.json").read_text(encoding="utf-8"))
    rebuilt = build_comparison_report(before, after, threshold="high")
    if comparison != rebuilt:
        raise SystemExit("Public comparison.json is stale; regenerate the Proof Loop")
    if before["toolVersion"] != __version__ or after["toolVersion"] != __version__:
        raise SystemExit("Public source reports were not generated by the current PPTLint version")

    overall = comparison["scores"]["overall"]
    resolved = len(comparison["resolved"])
    new_high = sum(
        1
        for item in comparison["new"]
        if item.get("confidence") == "high" and item.get("severity") in {"high", "critical"}
    )
    current_claims = {
        ROOT / "site" / "index.html": [f'{overall["before"]} → {overall["after"]}', str(resolved)],
        ROOT / "README.zh-CN.md": [f'{overall["before"]} → {overall["after"]}', str(resolved)],
        ROOT / "README.md": [f'{overall["before"]} → {overall["after"]}', str(resolved)],
        ROOT / "site" / "lab" / "index.html": [f'{overall["before"]} → {overall["after"]}'],
    }
    for path, snippets in current_claims.items():
        text = path.read_text(encoding="utf-8")
        missing = [snippet for snippet in snippets if snippet not in text]
        if missing:
            raise SystemExit(f"{path.relative_to(ROOT)} is missing current proof values: {missing}")
    if new_high != 0:
        raise SystemExit("Public proof introduced a new high-confidence problem")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
