from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    project = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    project_section = project.split("[project]", 1)[1].split("\n[", 1)[0]
    project_match = re.search(r'^version\s*=\s*"([^"]+)"', project_section, re.MULTILINE)
    if project_match is None:
        raise SystemExit("pyproject.toml has no project version")
    version = project_match.group(1)
    module = (ROOT / "src" / "decklint" / "__init__.py").read_text(encoding="utf-8")
    match = re.search(r'__version__\s*=\s*"([^"]+)"', module)
    if match is None or match.group(1) != version:
        raise SystemExit("pyproject.toml and decklint.__version__ do not match")
    changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    if f"### {version} —" not in changelog:
        raise SystemExit(f"CHANGELOG.md has no {version} release entry")
    proof = json.loads((ROOT / "site/proof-loop/comparison.json").read_text(encoding="utf-8"))
    for name in ("before", "after"):
        report = json.loads((ROOT / f"site/proof-loop/{name}.json").read_text(encoding="utf-8"))
        if report.get("toolVersion") != version:
            raise SystemExit(f"site/proof-loop/{name}.json was not generated by {version}")
    validation = json.loads(
        (ROOT / "validation/public-sample-validation.json").read_text(encoding="utf-8")
    )
    if validation.get("toolVersion") != version:
        raise SystemExit("Public sample validation version does not match the package")
    cases = json.loads((ROOT / "site/lab/cases.json").read_text(encoding="utf-8"))
    if cases.get("version") != version:
        raise SystemExit("Case Lab manifest version does not match the package")
    if (
        proof["scores"]["overall"] != {"before": 83, "after": 100, "delta": 17}
        or len(proof["resolved"]) != 103
        or len(proof["persistent"]) != 21
        or len(proof["new"]) != 3
    ):
        raise SystemExit("Committed Proof metrics do not match the v1.3.1 release contract")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
